spring:
  application:
    name: zuul-server
server:
  port: 5557
  servlet:
    context-path: /cloud
eureka:
  client:
    instance:
      preferIpAddress: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
zuul:
  routes:
    eureka-client: /client/**
    eureka-client2: /clienttwo/**
    eureka-feign-client: /clientfg/**
    eureka-feign-client2: /clienttwofg/**
    secured-client: /secured/**
    statistic-chain-client: /statistic/**
    secured-feign-client: /feign/**
  sensitiveHeaders: Cookie, Set-Cookie
# ribbon:
#   ReadTimeout: 60000